services:
  nginx-devlocal:
    container_name: "roadtraffic-nginx"
    build:
      context: ../.
      dockerfile: docker/nginx/Dockerfile
    command: [nginx, '-g', 'daemon off;']
    depends_on:
      - php-devlocal
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - "$PWD/..:/var/roadtraffic"
    ports:
      - "172.17.0.1:11280:80"
    networks:
      - roadtraffic-network

  php-devlocal:
    container_name: "roadtraffic-php"
    build:
      context: ../.
      dockerfile: docker/php/Dockerfile
      tags:
        - php-roadtraffic
    user: 1000:1000
    volumes:
      - "$PWD/..:/var/roadtraffic"
      - "$PWD/..:$PWD/.."
    working_dir: $PWD/..
    networks:
      - roadtraffic-network

  roadtraffic-swagger-ui:
    image: swaggerapi/swagger-ui:latest
    container_name: "roadtraffic-swagger-ui"
    restart: always
    environment:
      PORT_IPV6: 8080
      SUPPORTED_SUBMIT_METHODS: "['get', 'post', 'put', 'delete', 'patch']"
      SWAGGER_JSON: /v1/doc.yaml
    volumes:
      - ./swagger/v1:/v1
    ports:
      - "172.17.0.1:11202:8080"
    networks:
      - roadtraffic-network

networks:
  roadtraffic-network:
    driver: bridge
    name: roadtraffic-network
    enable_ipv6: true
    ipam:
      config:
        - subnet: fdff:1:2c::/112
          gateway: fdff:1:2c::1

volumes:
  roadtraffic-db:
